# buildconfig.yaml
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  # NO resourceVersion should be here
  name: flask-hello-world
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/ruslanmv/flask-hello-world.git"
      ref: main
    contextDir: .
  strategy:
    type: Docker
    dockerStrategy:
      resources:
        requests:
          cpu:    "1"
          memory: "128Mi"
        limits:
          cpu:    "2"
          memory: "256Mi"
  resources:
    requests:
      cpu:    "1"
      memory: "128Mi"
    limits:
      cpu:    "2"
      memory: "256Mi"
  output:
    to:
      kind: ImageStreamTag
      name: "flask-hello-world:latest"
  triggers:
    - type: ConfigChange
    - type: ImageChange