# buildconfig.yaml
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: flask-hello-world
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/ruslanmv/flask-hello-world.git"
      ref: main
    contextDir: .
  strategy:
    type: Docker
    dockerStrategy:
      resources:
        requests:
          cpu:    "1"      # request 1 core
          memory: "128Mi"  # request 128Mi
        limits:
          cpu:    "2"      # limit 2 cores
          memory: "256Mi"  # limit 256Mi
  resources:                      # applies to git-clone & manage-dockerfile too
    requests:
      cpu:    "1"
      memory: "128Mi"
    limits:
      cpu:    "2"
      memory: "256Mi"
  output:
    to:
      kind: ImageStreamTag
      name: "flask-hello-world:latest"
  triggers:
    - type: ConfigChange
    - type: ImageChange
