apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: flask-hello-world
spec:
  # 1) Source from your GitHub repository
  source:
    type: Git
    git:
      uri: "https://github.com/ruslanmv/flask-hello-world.git"
      ref: main
    contextDir: .
  
  # 2) Docker build strategy with per-step resources
  strategy:
    type: Docker
    dockerStrategy:
      resources:
        requests:
          cpu:    "10m"    # must be ≤ your requests.cpu quota (3)
          memory: "64Mi"   # must be ≤ your requests.memory quota (6Gi)
        limits:
          cpu:    "50m"    # must be ≤ your limits.cpu quota (6)
          memory: "128Mi"  # must be ≤ your limits.memory quota (12Gi)
  
  # 3) Top-level resources also apply to git-clone & manage-dockerfile steps
  resources:
    requests:
      cpu:    "10m"
      memory: "64Mi"
    limits:
      cpu:    "50m"
      memory: "128Mi"

  # 4) Send the built image into this ImageStreamTag
  output:
    to:
      kind: ImageStreamTag
      name: "flask-hello-world:latest"

  # 5) Automatically rebuild on config or image changes
  triggers:
    - type: ConfigChange
    - type: ImageChange
